var EventManager=function(){function k(a,b,c,d){if(null!==c&&(!a||r(b))){var g=p(b);null===a?a=o:!s||a.self===window?a=a.uniqueID=a:void 0===a.uniqueID&&(a.uniqueID=d?d:(a.localName||"element")+(new Date).valueOf());var e=a,b=g?t(b):b;if(!u(e,b,c)){a=e.uniqueID||e;d=b;h[a]||(h[a]=[]);h[a][d]||(h[a][d]=[]);h[a][d][h[a][d].length]=c;var f=b;if(e!==o&&!(1<h[e.uniqueID][f].length)){var l=g?v:w;e.attachEvent&&e!==window?(e["e"+f+l]=l,e[f+l]=function(){e["e"+f+l](window.event)},e.attachEvent("on"+f,e[f+
l])):e.addEventListener(f,l,!1);n[f]=e}}}}function i(a,b,c){if(null!==c&&(!a||r(b))){var d=p(b),b=d?t(b):b;var g=a?a.uniqueID:o,e=b;if(q(g,e)){for(var f=h[g][e],l=f.length;-1<--l;)f[l]==c&&f.splice(l,1);1>h[g][e].length&&(h[g][e]=void 0,delete h[g][e])}x(a,b,d)}}function u(a,b,c){if(!q(a,b))return!1;for(var a=h[a][b],d=a.length;-1<--d;)if(b=a[d],b===c)return!0;return!1}function q(a,b){return void 0===h[a]||void 0===h[a][b]?!1:!0}function x(a,b,c){if(a!==o){var d;d=a.uniqueID;d=void 0===h[d]?!0:!h[d][b]||
void 0===h[d][b];if(d){c=c?v:w;a.detachEvent&&a!==window?(a.detachEvent("on"+b,a[b+c]),a[b+c]=null):a.removeEventListener(b,c,!1);n[b]=void 0;var g,e;for(e in h[a.uniqueID])g=e;void 0===g&&(a.uniqueID=void 0,delete h[a.uniqueID])}}}function t(a){return"deviceorientation"===a&&void 0!==window.DeviceOrientationEvent?a:"devicemotion"}function p(a){if("deviceorientation"===a||"devicemotion"===a)if(void 0!==window.DeviceOrientationEvent||void 0!==window.DeviceMotionEvent)return!0;return!1}function r(a){if(p(a))return!0;
var b=document.createElement("div"),a="on"+a,c=a in b;c||(b.setAttribute(a,"return;"),c="function"==typeof b[a]);return c}function y(a,b,c,d,g){b=z(b,c,!0);r(b.eventType)&&(g?k(a,b.eventType,b.handler,d):i(a,b.eventType,b.handler))}function z(a,b,c){switch(a){case "click":case "touchstart":case "mousedown":a=j?"touchstart":"mousedown"===a?"mousedown":"click";void 0===b&&c&&(b=_mouseDown_handler);break;case "mousemove":case "touchmove":a=j?"touchmove":"mousemove";void 0===b&&c&&(b=_mouseMove_handler);
break;case "touchend":case "mouseup":a=j?"touchend":"mouseup",void 0===b&&c&&(b=_mouseUp_handler)}return{eventType:a,handler:b}}function B(a){a.preventDefault()?a.preventDefault():a.returnValue=!1;a.stopPropagation();var b=a.currentTarget||a.srcElement,c=h[b.uniqueID][a.type];if(void 0!==c)for(var d,g=c.length;-1<--g;)if(d=c[g]){var e=a,f={x:0,y:0,uniqueID:-1,event:null},l=document.body.scrollLeft,k=document.documentElement.scrollLeft,i=document.body.scrollTop,C=document.documentElement.scrollTop,
m=b.offsetLeft||0,o=b.offsetTop||0,j=void 0,n=void 0;e.pageX||e.pageY?(j=e.pageX,n=e.pageY):(j=e.clientX+l+k,n=e.clientY+i+C);j-=m;n-=o;f.x=j;f.y=n;f.event=e;f.uniqueID=f.uniqueID||-1;d(f)}}function D(a){a.preventDefault()?a.preventDefault():a.returnValue=!1;a.stopPropagation();var b=a.currentTarget||a.srcElement,c={x:null,y:null,isPressed:!1,id:0,event:null,uniqueID:-1},d=document.body.scrollLeft,g=document.documentElement.scrollLeft,e=document.body.scrollTop,f=document.documentElement.scrollTop,
l=b.offsetLeft||0,k=b.offsetTop||0,i,j,m=a.touches.length,m=a.touches[m-1];switch(a.type){case "touchstart":1==a.touches.length&&(c.isPressed=!0);i=m.pageX;j=m.pageY;break;case "touchmove":m=a.touches[0];m.pageX||m.pageY?(i=m.pageX,j=m.pageY):(i=m.clientX+d+g,j=m.clientY+e+f);i-=l;j-=k;break;case "touchend":c.isPressed=!1,c.x=null,c.y=null}c.x=i;c.y=j;c.event=a;uniqueID=b.uniqueID||-1;if(A&&(d=b.innerWidth||b.clientWidth,g=b.innerHeight||b.clientHeight,e=c.x,f=c.y,0>e||e>0+d||0>f||f>0+g))return;a=
h[b.uniqueID][a.type];if(void 0!==a)for(d=a.length;-1<--d;)(b=a[d])&&b(c)}function v(a){a.preventDefault()?a.preventDefault():a.returnValue=!1;a.stopPropagation();var b={gamma:0,beta:0,alpha:0,cssRotation:0,absolute:!1,event:null};b.event=a;switch(a.type){case "deviceorientation":b.alpha=Math.round(a.alpha);b.beta=-1*Math.round(a.beta);b.gamma=Math.round(a.gamma);b.cssRotation="rotate("+b.gamma+"deg) rotate3d(1,0,0, "+b.beta+"deg)";break;case "devicemotion":var c=a.accelerationIncludingGravity,d=
1;0<c.z&&(d=-1);b.alpha=d;b.beta=Math.round(90*((c.y+9.81)/9.81)*d)-90;b.gamma=-1*Math.round(-90*(c.x/9.81));b.cssRotation="rotate("+b.gamma+"deg) rotate3d(1,0,0, "+b.beta+"deg)"}if(window.orientation){switch(window.orientation){case 0:c=b.gamma;d=b.beta;break;case 180:c=-1*b.gamma;d=-1*b.beta;break;case 90:c=-1*b.beta;d=b.gamma;break;case -90:c=b.beta;d=-1*b.gamma;break;default:c=b.gamma,d=b.beta}b.gamma=c;b.beta=d}a.absolute&&(b.absolute=a.absolute);a=h[a.target][a.type];if(void 0!==a)for(d=a.length;-1<
--d;)(c=a[d])&&c(b)}var o="genericEvent",j="ontouchstart"in window,w=j?D:B,h=[],n=[],s=!1,A=!1;return{addListener:k,removeListener:i,autoAddListener:function(a,b,c,d){y(a,b,c,d,!0)},autoRemoveListener:function(a,b,c){y(a,b,c,void 0,!1)},swapHandler:function(a,b,c,d){var a=a?a.uniqueID:o,g=z(b,c,!1),b=j?g.eventType:b;if(q(a,b)&&u(a,b,c)){b=h[a][b];for(g=b.length;-1<--g;)a=b[g],a==c&&(b[g]=d)}},captureEvents:function(a,b,c,d,g,e,f){null!==a&&(null===f&&(f=!0),_captureContext=a,j?(f?k(a,"touchstart",
b,void 0):i(a,"touchstart",b),f?k(a,"touchmove",c,void 0):i(a,"touchmove",c),f?k(a,"touchend",d,void 0):i(a,"touchend",d)):(f?k(a,"mousedown",b,void 0):i(a,"mousedown",b),f?k(a,"mousemove",c,void 0):i(a,"mousemove",c),f?k(a,"mouseup",d,void 0):i(a,"mouseup",d),f?k(a,"mouseover",g,void 0):i(a,"mouseover",g),f?k(a,"mouseover",g,void 0):i(a,"mouseover",g),f?k(a,"mouseout",e,void 0):i(a,"mouseout",e)))},dispatch:function(a,b){if(q(o,a))for(var c=h[o][a],d,g=c.length;-1<--g;)(d=c[g])&&d(b)},dispose:function(){var a,
b;for(a in n)b=n[a],b.uniqueID&&(b.uniqueID=void 0),x(b,a,p(a));_mouseOut_handler=_mouseOver_handler=_mouseMove_handler=_mouseUp_handler=_mouseDown_handler=_click_handler=void 0;h=[];n=[]},useUniqueID:function(a){s=a},useTouchBounds:function(a){A=a}}}();